# Generated by Django 4.0.2 on 2022-02-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boo',
            new_name='Book',
        ),
    ]
